# config.yaml
data:
  raw_data_dir: "../data/raw/"
  processed_data_path: "../output/processed_sensor_data.csv"
  model_output_path: "../output/models/"
  log_path: "../output/logs/"
  evaluation_output_path: "../output/evaluation/"

output_paths:
  converted_csv: "../output/converted_csv/"
  processed_data: "../output/processed_sensor_data.csv"
  models: "../output/models/"
  logs: "../output/logs/"
  evaluation: "../output/evaluation/"

model_params:
  random_forest:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, None]
    min_samples_leaf: [1, 2, 4]
  xgboost:
    n_estimators: [100, 200]
    max_depth: [3, 6, 10]
    learning_rate: [0.01, 0.1]
    subsample: [0.7, 1.0]
  lightgbm:
    n_estimators: [100, 200]
    max_depth: [-1, 10, 20]
    learning_rate: [0.01, 0.1]
    num_leaves: [31, 50]
  gradient_boosting:
    n_estimators: [100, 200]
    max_depth: [3, 5, 10]
    learning_rate: [0.01, 0.1]

evaluation:
  test_size: 0.3
  random_state: 42

logging:
  level: "INFO"

model_selection:
  train_random_forest: True
  train_xgboost: True
  train_lightgbm: True
  train_gradient_boosting: True
  train_stacking: True

environment: "development"
